#pragma once

// clang-format off
#define SERIALIZE_ARG_COUNT(...) SERIALIZE_MARCO_EXPAND(SERIALIZE_INTERNAL_ARG_COUNT(0, ##__VA_ARGS__,\
	64, 63, 62, 61, 60, \
	59, 58, 57, 56, 55, 54, 53, 52, 51, 50, \
	49, 48, 47, 46, 45, 44, 43, 42, 41, 40, \
	39, 38, 37, 36, 35, 34, 33, 32, 31, 30, \
	29, 28, 27, 26, 25, 24, 23, 22, 21, 20, \
	19, 18, 17, 16, 15, 14, 13, 12, 11, 10, \
	 9,  8,  7,  6,  5,  4,  3,  2,  1,  0))

#define SERIALIZE_INTERNAL_ARG_COUNT(\
	 _0,  _1,  _2,  _3,  _4,  _5,  _6,  _7,  _8,  _9, \
	_10, _11, _12, _13, _14, _15, _16, _17, _18, _19, \
	_20, _21, _22, _23, _24, _25, _26, _27, _28, _29, \
	_30, _31, _32, _33, _34, _35, _36, _37, _38, _39, \
	_40, _41, _42, _43, _44, _45, _46, _47, _48, _49, \
	_50, _51, _52, _53, _54, _55, _56, _57, _58, _59, \
	_60, _61, _62, _63, _64, N, ...) N

#define SERIALIZE_CONCAT_(l, r) l ## r
#define SERIALIZE_CONCAT(l, r) SERIALIZE_CONCAT_(l, r)

#define SERIALIZE_MARCO_EXPAND(...) __VA_ARGS__

#define SERIALIZE_DOARG0(s,f,Type,o)
#define SERIALIZE_DOARG1(s,f,Type,t,...)  SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG0(s,f,Type,__VA_ARGS__))  s f(0,Type,t)
#define SERIALIZE_DOARG2(s,f,Type,t,...)  SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG1(s,f,Type,__VA_ARGS__))  s f(1,Type,t)
#define SERIALIZE_DOARG3(s,f,Type,t,...)  SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG2(s,f,Type,__VA_ARGS__))  s f(2,Type,t)
#define SERIALIZE_DOARG4(s,f,Type,t,...)  SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG3(s,f,Type,__VA_ARGS__))  s f(3,Type,t)
#define SERIALIZE_DOARG5(s,f,Type,t,...)  SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG4(s,f,Type,__VA_ARGS__))  s f(4,Type,t)
#define SERIALIZE_DOARG6(s,f,Type,t,...)  SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG5(s,f,Type,__VA_ARGS__))  s f(5,Type,t)
#define SERIALIZE_DOARG7(s,f,Type,t,...)  SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG6(s,f,Type,__VA_ARGS__))  s f(6,Type,t)
#define SERIALIZE_DOARG8(s,f,Type,t,...)  SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG7(s,f,Type,__VA_ARGS__)) s f(7,Type,t)
#define SERIALIZE_DOARG9(s,f,Type,t,...)  SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG8(s,f,Type,__VA_ARGS__)) s f(8,Type,t)
#define SERIALIZE_DOARG10(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG9(s,f,Type,__VA_ARGS__)) s f(9,Type,t)
#define SERIALIZE_DOARG11(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG10(s,f,Type,__VA_ARGS__)) s f(10,Type,t)
#define SERIALIZE_DOARG12(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG11(s,f,Type,__VA_ARGS__)) s f(11,Type,t)
#define SERIALIZE_DOARG13(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG12(s,f,Type,__VA_ARGS__)) s f(12,Type,t)
#define SERIALIZE_DOARG14(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG13(s,f,Type,__VA_ARGS__)) s f(13,Type,t)
#define SERIALIZE_DOARG15(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG14(s,f,Type,__VA_ARGS__)) s f(14,Type,t)
#define SERIALIZE_DOARG16(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG15(s,f,Type,__VA_ARGS__)) s f(15,Type,t)
#define SERIALIZE_DOARG17(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG16(s,f,Type,__VA_ARGS__)) s f(16,Type,t)
#define SERIALIZE_DOARG18(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG17(s,f,Type,__VA_ARGS__)) s f(17,Type,t)
#define SERIALIZE_DOARG19(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG18(s,f,Type,__VA_ARGS__)) s f(18,Type,t)
#define SERIALIZE_DOARG20(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG19(s,f,Type,__VA_ARGS__)) s f(19,Type,t)
#define SERIALIZE_DOARG21(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG20(s,f,Type,__VA_ARGS__)) s f(20,Type,t)
#define SERIALIZE_DOARG22(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG21(s,f,Type,__VA_ARGS__)) s f(21,Type,t)
#define SERIALIZE_DOARG23(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG22(s,f,Type,__VA_ARGS__)) s f(22,Type,t)
#define SERIALIZE_DOARG24(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG23(s,f,Type,__VA_ARGS__)) s f(23,Type,t)
#define SERIALIZE_DOARG25(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG24(s,f,Type,__VA_ARGS__)) s f(24,Type,t)
#define SERIALIZE_DOARG26(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG25(s,f,Type,__VA_ARGS__)) s f(25,Type,t)
#define SERIALIZE_DOARG27(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG26(s,f,Type,__VA_ARGS__)) s f(26,Type,t)
#define SERIALIZE_DOARG28(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG27(s,f,Type,__VA_ARGS__)) s f(27,Type,t)
#define SERIALIZE_DOARG29(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG28(s,f,Type,__VA_ARGS__)) s f(28,Type,t)
#define SERIALIZE_DOARG30(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG29(s,f,Type,__VA_ARGS__)) s f(29,Type,t)
#define SERIALIZE_DOARG31(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG30(s,f,Type,__VA_ARGS__)) s f(30,Type,t)
#define SERIALIZE_DOARG32(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG31(s,f,Type,__VA_ARGS__)) s f(31,Type,t)
#define SERIALIZE_DOARG33(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG32(s,f,Type,__VA_ARGS__)) s f(32,Type,t)
#define SERIALIZE_DOARG34(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG33(s,f,Type,__VA_ARGS__)) s f(33,Type,t)
#define SERIALIZE_DOARG35(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG34(s,f,Type,__VA_ARGS__)) s f(34,Type,t)
#define SERIALIZE_DOARG36(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG35(s,f,Type,__VA_ARGS__)) s f(35,Type,t)
#define SERIALIZE_DOARG37(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG36(s,f,Type,__VA_ARGS__)) s f(36,Type,t)
#define SERIALIZE_DOARG38(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG37(s,f,Type,__VA_ARGS__)) s f(37,Type,t)
#define SERIALIZE_DOARG39(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG38(s,f,Type,__VA_ARGS__)) s f(38,Type,t)
#define SERIALIZE_DOARG40(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG39(s,f,Type,__VA_ARGS__)) s f(39,Type,t)
#define SERIALIZE_DOARG41(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG40(s,f,Type,__VA_ARGS__)) s f(40,Type,t)
#define SERIALIZE_DOARG42(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG41(s,f,Type,__VA_ARGS__)) s f(41,Type,t)
#define SERIALIZE_DOARG43(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG42(s,f,Type,__VA_ARGS__)) s f(42,Type,t)
#define SERIALIZE_DOARG44(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG43(s,f,Type,__VA_ARGS__)) s f(43,Type,t)
#define SERIALIZE_DOARG45(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG44(s,f,Type,__VA_ARGS__)) s f(44,Type,t)
#define SERIALIZE_DOARG46(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG45(s,f,Type,__VA_ARGS__)) s f(45,Type,t)
#define SERIALIZE_DOARG47(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG46(s,f,Type,__VA_ARGS__)) s f(46,Type,t)
#define SERIALIZE_DOARG48(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG47(s,f,Type,__VA_ARGS__)) s f(47,Type,t)
#define SERIALIZE_DOARG49(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG48(s,f,Type,__VA_ARGS__)) s f(48,Type,t)
#define SERIALIZE_DOARG50(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG49(s,f,Type,__VA_ARGS__)) s f(49,Type,t)
#define SERIALIZE_DOARG51(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG50(s,f,Type,__VA_ARGS__)) s f(50,Type,t)
#define SERIALIZE_DOARG52(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG51(s,f,Type,__VA_ARGS__)) s f(51,Type,t)
#define SERIALIZE_DOARG53(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG52(s,f,Type,__VA_ARGS__)) s f(52,Type,t)
#define SERIALIZE_DOARG54(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG53(s,f,Type,__VA_ARGS__)) s f(53,Type,t)
#define SERIALIZE_DOARG55(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG54(s,f,Type,__VA_ARGS__)) s f(54,Type,t)
#define SERIALIZE_DOARG56(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG55(s,f,Type,__VA_ARGS__)) s f(55,Type,t)
#define SERIALIZE_DOARG57(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG56(s,f,Type,__VA_ARGS__)) s f(56,Type,t)
#define SERIALIZE_DOARG58(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG57(s,f,Type,__VA_ARGS__)) s f(57,Type,t)
#define SERIALIZE_DOARG59(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG58(s,f,Type,__VA_ARGS__)) s f(58,Type,t)
#define SERIALIZE_DOARG60(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG59(s,f,Type,__VA_ARGS__)) s f(59,Type,t)
#define SERIALIZE_DOARG61(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG60(s,f,Type,__VA_ARGS__)) s f(60,Type,t)
#define SERIALIZE_DOARG62(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG61(s,f,Type,__VA_ARGS__)) s f(61,Type,t)
#define SERIALIZE_DOARG63(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG62(s,f,Type,__VA_ARGS__)) s f(62,Type,t)
#define SERIALIZE_DOARG64(s,f,Type,t,...) SERIALIZE_MARCO_EXPAND(SERIALIZE_DOARG63(s,f,Type,__VA_ARGS__)) s f(63,Type,t)

#define SERIALIZE_MAKE_ARGS0(Type)
#define SERIALIZE_MAKE_ARGS1(Type)     Type
#define SERIALIZE_MAKE_ARGS2(Type)     SERIALIZE_MAKE_ARGS1(Type), Type
#define SERIALIZE_MAKE_ARGS3(Type)     SERIALIZE_MAKE_ARGS2(Type), Type
#define SERIALIZE_MAKE_ARGS4(Type)     SERIALIZE_MAKE_ARGS3(Type), Type
#define SERIALIZE_MAKE_ARGS5(Type)     SERIALIZE_MAKE_ARGS4(Type), Type
#define SERIALIZE_MAKE_ARGS6(Type)     SERIALIZE_MAKE_ARGS5(Type), Type
#define SERIALIZE_MAKE_ARGS7(Type)     SERIALIZE_MAKE_ARGS6(Type), Type
#define SERIALIZE_MAKE_ARGS8(Type)     SERIALIZE_MAKE_ARGS7(Type), Type
#define SERIALIZE_MAKE_ARGS9(Type)     SERIALIZE_MAKE_ARGS8(Type), Type
#define SERIALIZE_MAKE_ARGS10(Type)    SERIALIZE_MAKE_ARGS9(Type), Type
#define SERIALIZE_MAKE_ARGS11(Type)    SERIALIZE_MAKE_ARGS10(Type), Type
#define SERIALIZE_MAKE_ARGS12(Type)    SERIALIZE_MAKE_ARGS11(Type), Type
#define SERIALIZE_MAKE_ARGS13(Type)    SERIALIZE_MAKE_ARGS12(Type), Type
#define SERIALIZE_MAKE_ARGS14(Type)    SERIALIZE_MAKE_ARGS13(Type), Type
#define SERIALIZE_MAKE_ARGS15(Type)    SERIALIZE_MAKE_ARGS14(Type), Type
#define SERIALIZE_MAKE_ARGS16(Type)    SERIALIZE_MAKE_ARGS15(Type), Type
#define SERIALIZE_MAKE_ARGS17(Type)    SERIALIZE_MAKE_ARGS16(Type), Type
#define SERIALIZE_MAKE_ARGS18(Type)    SERIALIZE_MAKE_ARGS17(Type), Type
#define SERIALIZE_MAKE_ARGS19(Type)    SERIALIZE_MAKE_ARGS18(Type), Type
#define SERIALIZE_MAKE_ARGS20(Type)    SERIALIZE_MAKE_ARGS19(Type), Type
#define SERIALIZE_MAKE_ARGS21(Type)    SERIALIZE_MAKE_ARGS20(Type), Type
#define SERIALIZE_MAKE_ARGS22(Type)    SERIALIZE_MAKE_ARGS21(Type), Type
#define SERIALIZE_MAKE_ARGS23(Type)    SERIALIZE_MAKE_ARGS22(Type), Type
#define SERIALIZE_MAKE_ARGS24(Type)    SERIALIZE_MAKE_ARGS23(Type), Type
#define SERIALIZE_MAKE_ARGS25(Type)    SERIALIZE_MAKE_ARGS24(Type), Type
#define SERIALIZE_MAKE_ARGS26(Type)    SERIALIZE_MAKE_ARGS25(Type), Type
#define SERIALIZE_MAKE_ARGS27(Type)    SERIALIZE_MAKE_ARGS26(Type), Type
#define SERIALIZE_MAKE_ARGS28(Type)    SERIALIZE_MAKE_ARGS27(Type), Type
#define SERIALIZE_MAKE_ARGS29(Type)    SERIALIZE_MAKE_ARGS28(Type), Type
#define SERIALIZE_MAKE_ARGS30(Type)    SERIALIZE_MAKE_ARGS29(Type), Type
#define SERIALIZE_MAKE_ARGS31(Type)    SERIALIZE_MAKE_ARGS30(Type), Type
#define SERIALIZE_MAKE_ARGS32(Type)    SERIALIZE_MAKE_ARGS31(Type), Type
#define SERIALIZE_MAKE_ARGS33(Type)    SERIALIZE_MAKE_ARGS32(Type), Type
#define SERIALIZE_MAKE_ARGS34(Type)    SERIALIZE_MAKE_ARGS33(Type), Type
#define SERIALIZE_MAKE_ARGS35(Type)    SERIALIZE_MAKE_ARGS34(Type), Type
#define SERIALIZE_MAKE_ARGS36(Type)    SERIALIZE_MAKE_ARGS35(Type), Type
#define SERIALIZE_MAKE_ARGS37(Type)    SERIALIZE_MAKE_ARGS36(Type), Type
#define SERIALIZE_MAKE_ARGS38(Type)    SERIALIZE_MAKE_ARGS37(Type), Type
#define SERIALIZE_MAKE_ARGS39(Type)    SERIALIZE_MAKE_ARGS38(Type), Type
#define SERIALIZE_MAKE_ARGS40(Type)    SERIALIZE_MAKE_ARGS39(Type), Type
#define SERIALIZE_MAKE_ARGS41(Type)    SERIALIZE_MAKE_ARGS40(Type), Type
#define SERIALIZE_MAKE_ARGS42(Type)    SERIALIZE_MAKE_ARGS41(Type), Type
#define SERIALIZE_MAKE_ARGS43(Type)    SERIALIZE_MAKE_ARGS42(Type), Type
#define SERIALIZE_MAKE_ARGS44(Type)    SERIALIZE_MAKE_ARGS43(Type), Type
#define SERIALIZE_MAKE_ARGS45(Type)    SERIALIZE_MAKE_ARGS44(Type), Type
#define SERIALIZE_MAKE_ARGS46(Type)    SERIALIZE_MAKE_ARGS45(Type), Type
#define SERIALIZE_MAKE_ARGS47(Type)    SERIALIZE_MAKE_ARGS46(Type), Type
#define SERIALIZE_MAKE_ARGS48(Type)    SERIALIZE_MAKE_ARGS47(Type), Type
#define SERIALIZE_MAKE_ARGS49(Type)    SERIALIZE_MAKE_ARGS48(Type), Type
#define SERIALIZE_MAKE_ARGS50(Type)    SERIALIZE_MAKE_ARGS49(Type), Type
#define SERIALIZE_MAKE_ARGS51(Type)    SERIALIZE_MAKE_ARGS50(Type), Type
#define SERIALIZE_MAKE_ARGS52(Type)    SERIALIZE_MAKE_ARGS51(Type), Type
#define SERIALIZE_MAKE_ARGS53(Type)    SERIALIZE_MAKE_ARGS52(Type), Type
#define SERIALIZE_MAKE_ARGS54(Type)    SERIALIZE_MAKE_ARGS53(Type), Type
#define SERIALIZE_MAKE_ARGS55(Type)    SERIALIZE_MAKE_ARGS54(Type), Type
#define SERIALIZE_MAKE_ARGS56(Type)    SERIALIZE_MAKE_ARGS55(Type), Type
#define SERIALIZE_MAKE_ARGS57(Type)    SERIALIZE_MAKE_ARGS56(Type), Type
#define SERIALIZE_MAKE_ARGS58(Type)    SERIALIZE_MAKE_ARGS57(Type), Type
#define SERIALIZE_MAKE_ARGS59(Type)    SERIALIZE_MAKE_ARGS58(Type), Type
#define SERIALIZE_MAKE_ARGS60(Type)    SERIALIZE_MAKE_ARGS59(Type), Type
#define SERIALIZE_MAKE_ARGS61(Type)    SERIALIZE_MAKE_ARGS60(Type), Type
#define SERIALIZE_MAKE_ARGS62(Type)    SERIALIZE_MAKE_ARGS61(Type), Type
#define SERIALIZE_MAKE_ARGS63(Type)    SERIALIZE_MAKE_ARGS62(Type), Type
#define SERIALIZE_MAKE_ARGS64(Type)    SERIALIZE_MAKE_ARGS63(Type), Type


#define SERIALIZE_MAKE_ARGS(Type,Count) \
  SERIALIZE_CONCAT(SERIALIZE_MAKE_ARGS,Count)(Type)

#define SERIALIZE_EXPAND_EACH_(sepatator,fun,Type, ...) \
		SERIALIZE_MARCO_EXPAND(SERIALIZE_CONCAT(SERIALIZE_DOARG,SERIALIZE_ARG_COUNT(__VA_ARGS__))(sepatator,fun,Type,__VA_ARGS__))
#define SERIALIZE_EXPAND_EACH(sepatator,fun,Type, ...) \
		SERIALIZE_EXPAND_EACH_(sepatator,fun,Type,__VA_ARGS__)
